# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e5f3ddc7b5c723862a433e2276487bdfc7e0c4bc8212fc29be545cfa354f1a06ddc58200366a1abb86d0bb763e8a76571ab0b8428b4ae7e139cd0455cb3952

test:
  secret_key_base: 6c710005aa82ae17495a190b2be1f04cfb94069ecb7f91376c6431aa7d592a8fc9b2d8f8869964ea99184d3f438e3568346478438cad932a5b2ad35012311e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
